### ISSUE TITLE
Make the wp-easy plugin a must use plugin

### ISSUE THREAD

**Issue by drewbaker** [drewbaker/wp-easy-theme#7]
Either need to add it to the plugin manifest, or the native "must-use" plugins, just as long as it's easy to update the wp-easy plugin for sites in the future.

**Comment by rsm0128** [comment]
I made the `wp-easy` as required plugin.
https://github.com/drewbaker/wp-easy-theme/pull/11/commits/03af899a1c3cae8c11f44240f7b2b0b2c7127e33
